# Generated by Django 5.2.11 on 2026-03-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('tech', 'Technology'), ('programming', 'Programming'), ('ai', 'Artificial Intelligence'), ('web', 'Web Development'), ('python', 'Python'), ('news', 'News'), ('tutorial', 'Tutorial'), ('tips', 'Tips & Tricks'), ('career', 'Career'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
